### ISSUE TITLE
1Mg company will mapped with which alphabet??

### ISSUE THREAD

**Issue by code1511** [Kaustubh-Natuskar/companies-to-apply#118]
https://www.1mg.com/jobs

**Comment by Kaustubh-Natuskar** [comment]
Hey @iyoushe1703 has made a new section 0-9 . Please make sure that you have forked latest main form main repository.

**Comment by code1511** [comment]
Okay

**Comment by Kaustubh-Natuskar** [comment]
1mg is already in list.

**Comment by code1511** [comment]
Yeah found it
