### ISSUE TITLE
Career page of HBO, Dukaan and Amway .

### ISSUE THREAD

**Issue by ayush-sleeping** [Kaustubh-Natuskar/companies-to-apply#169]
Hey @Kaustubh-Natuskar , ` " Assign " `  me this issue , <br>
I want to add following company name and their career page in this awesome repository .  <br>
HBO, Dukaan and Amway <br>
--  I want to work on this issue.   --

**Comment by Kaustubh-Natuskar** [comment]
> Hey @Kaustubh-Natuskar , ` " Assign " `  me this issue , <br>
> I want to add following company name and their career page in this awesome repository .  <br>
> HBO, Dukaan and Amway <br>
> --  I want to work on this issue.   --

Okay add these, then make  a PR. Don't forget to read the guidelines.
