### ISSUE TITLE
Readme Updatation

### ISSUE THREAD

**Issue by ayush-sleeping** [Kaustubh-Natuskar/companies-to-apply#173]
Hey @Kaustubh-Natuskar , I want to update this "Find Companies Alphabetically" section , 
and want to give it more Good look .  
You can see the difference , what I want to tell you in below Picture . 
<br>

## Now how it's looking :-

![Screenshot (708)](https://user-images.githubusercontent.com/76460132/143731618-fd69b787-f662-4af7-a1f7-9c4133fd5688.png)

<br>

## After updation , How it will look :-

![Screenshot (709)](https://user-images.githubusercontent.com/76460132/143731635-9064f0ae-51f5-4f66-8652-c5871f291404.png)

**Comment by ayush-sleeping** [comment]
Hey @Kaustubh-Natuskar , what do you think , let me know . 
<br>

**Comment by Kaustubh-Natuskar** [comment]
@ayush-sleeping do it. Thank you for recommendation 😃. Keep up the good work i'll add you as maintainer soon.
