### ISSUE TITLE
Incorrect Counter value and add Nutanix, Coinbase and publicis sapient

### ISSUE THREAD

**Issue by sohamchakravarty** [Kaustubh-Natuskar/companies-to-apply#58]
In B, there are duplicates. Please remove them and update the correct counter value.

Also please add the following companies.

1.   Nutanix - https://www.nutanix.com/company/careers
2.   Coinbase - https://www.coinbase.com/careers/positions
3.   publicis sapient - https://careers.publicissapient.com/

**Comment by Kaustubh-Natuskar** [comment]
ok
